/**
 * A real gateway, the dev server in front of it, and a `NessaClient` on it as
 * a surface of its own: what the checks against a real gateway start from
 * (`mcp-apps-gateway.mjs`, `gateway-window.mjs`); and an agent's turn on it,
 * sent and waited out (`agentTurn`).
 *
 * The gateway is `scripts/mcp-test-server/local-gateway.mjs`'s: a temporary
 * `ci` namespace on 127.0.0.1, with one agent's runtime (`options.agent`,
 * claude or codex) and the test MCP server as `mcptest`. It uses the agent's
 * own sign-in on this machine and creates no account; with `scripted` (a tool
 * name), it runs `scripts/mcp-test-server/scripted-agent.mjs` as that agent
 * instead, calling that tool, signed out (`scriptedCommand`). The credentials — the
 * owner token, and the panel's — are generated by the gateway, read from its
 * temporary directory, never printed, and removed with it.
 */
import { readdirSync, readFileSync } from "node:fs"
import { join, sep } from "node:path"
import { setTimeout as sleep } from "node:timers/promises"

import {
  MODELS,
  agentCommand,
  repoRoot,
  serverScript,
  startLocalGateway,
} from "../../../../scripts/mcp-test-server/local-gateway.mjs"
import { turnEnded } from "../../../../scripts/mcp-test-server/evidence.mjs"
import { CannotRun, log } from "./cli.mjs"
import { freePort, startDevServer } from "./server.mjs"

/**
 * The panel's credential as the gateway provisioned it: the one
 * `auth/surfaces/nessa-panel.token` under its directory, whichever namespace
 * holds it (`provisioning.rs` writes it, `surface_credential.rs` reads it for
 * the desktop window). It carries the panel's grants, not the owner's. Not
 * exactly one there is "could not run".
 */
export function panelCredential(gateway) {
  const file = join("auth", "surfaces", "nessa-panel.token")
  const found = readdirSync(gateway.directory, { recursive: true }).filter(
    (path) => String(path) === file || String(path).endsWith(sep + file),
  )
  if (found.length !== 1)
    throw new CannotRun(
      `the gateway provisioned ${found.length} panel credentials, not one`,
    )
  return readFileSync(join(gateway.directory, String(found[0])), "utf8").trim()
}

/**
 * How the gateway starts the scripted agent as `agent`'s runtime, with that
 * agent's model, calling `tool` once to each prompt.
 */
function scriptedCommand(agent, tool) {
  return {
    argv: [
      process.execPath,
      join(repoRoot, "scripts/mcp-test-server/scripted-agent.mjs"),
      agent,
      tool,
    ],
    model: MODELS[agent],
    path: null,
  }
}

/**
 * Starts the stack as `instance`, its client named after it and signed in
 * `as` the gateway's owner (the default) or its panel. With `scripted`, a tool
 * name, the scripted agent is the runtime and calls that tool. Resolves with
 * `{ url, mode, close, client, gateway, timings, token }`: `url` the dev
 * server's desktop page, `token()` the owner token, `close()` stops all three.
 * A gateway that does not start is "could not run", with its last output on
 * stderr.
 */
export async function startGatewayStack(
  options,
  instance,
  { as = "owner", scripted } = {},
) {
  const agent = options.agent
  if (!["claude", "codex"].includes(agent))
    throw new CannotRun(`--agent ${agent}: claude or codex`)
  const command = scripted ? scriptedCommand(agent, scripted) : agentCommand(agent)
  const timings = {}
  let started = Date.now()
  const gateway = await startLocalGateway({
    agent,
    port: await freePort(),
    instance,
    agentArgv: command.argv,
    model: command.model,
    path: command.path,
    mcpServer: { command: process.execPath, args: [serverScript] },
    signedOut: Boolean(scripted),
  }).catch((error) => {
    // What it said as it failed, on stderr; the result keeps one line.
    if (error.gatewayLog) log(error.gatewayLog.slice(-4000))
    throw new CannotRun(`the gateway did not start: ${error.message.split("\n")[0]}`)
  })
  timings.gatewayMs = Date.now() - started
  let dev = null
  let client = null
  // The gateway stops, and its directory with the credentials goes, whatever
  // the client or the dev server did as they closed.
  const close = async () => {
    try {
      client?.close()
      await dev?.close()
    } finally {
      if (!(await gateway.stop()))
        log(`the gateway (pid ${gateway.server.pid}) did not exit`)
    }
  }
  const token = () => readFileSync(gateway.token, "utf8").trim()
  try {
    started = Date.now()
    dev = await startDevServer(options, {
      NESSA_STAGE: "ci",
      VITE_NESSA_STAGE: "ci",
      NESSA_BROWSER_GATEWAY_URL: gateway.url,
    })
    timings.devServerMs = Date.now() - started
    // `@nessa/client` is TypeScript in this checkout.
    const { register } = await import("tsx/esm/api")
    register()
    const { NessaClient } = await import("@nessa/client")
    client = await NessaClient.connect({
      stage: "ci",
      url: gateway.url.replace(/^http/, "ws"),
      role: "surface",
      surface: { kind: "panel", instance },
      client: { id: instance, version: "0.1.0", platform: "node" },
      profile: "product",
      auth: { credential: as === "panel" ? panelCredential(gateway) : token() },
    })
    return { url: dev.url, mode: "dev", close, client, gateway, timings, token }
  } catch (error) {
    await close()
    throw error
  }
}

/** Waits up to `ms` for `check()` to be truthy, and says what it last was. */
export async function waitFor(check, ms) {
  const end = Date.now() + ms
  let value
  do {
    value = await check()
    if (value) return value
    await sleep(250)
  } while (Date.now() < end)
  return value
}

/**
 * Sends `text` in `conversationId` — creating the conversation first when
 * `create` — and reads the conversation each second until that turn ends,
 * handing each read to `onView` (which may answer the turn's permissions).
 * Resolves with `{ view, turn }`: the view in which the turn ended, and the
 * turn; whether it ended well is the caller's to judge. A conversation or
 * message the gateway refuses, or a turn that does not end within `seconds`,
 * is "could not run".
 */
export async function agentTurn(
  client,
  conversationId,
  text,
  { agent, create = false, seconds = 180, onView = async () => {} },
) {
  let before
  try {
    if (create) await client.conversation.create({ conversationId, agent })
    // The view's messages are its turns; this one is the one after `before`.
    before = (await client.conversation.read(conversationId)).messages.length
    await client.conversation.send(conversationId, text)
  } catch (error) {
    throw new CannotRun(
      `the gateway refused the ${agent} conversation (a live ${agent}: is it signed in on this machine?): ${error.message}`,
    )
  }
  let turn
  for (let i = 0; i < seconds; i += 1) {
    await sleep(1000)
    const view = await client.conversation.read(conversationId)
    await onView(view)
    turn = view.messages[before]
    if (turn && turnEnded(turn.status)) return { view, turn }
  }
  throw new CannotRun(
    `${agent}'s turn did not end within ${seconds} s; it was last ${turn?.status ?? "not listed"}`,
  )
}
