/**
 * A real gateway, the dev server in front of it, and a `NessaClient` on it as
 * a surface of its own: what the checks against a real gateway start from
 * (`mcp-apps-gateway.mjs`, `gateway-window.mjs`); and an agent's turn on it,
 * sent and waited out (`agentTurn`).
 *
 * The gateway is `scripts/mcp-test-server/local-gateway.mjs`'s: a temporary
 * `ci` namespace on 127.0.0.1, with one agent's runtime (`options.agent`,
 * claude or codex) and the test MCP server as `mcptest`. It uses the agent's
 * own sign-in on this machine and creates no account; with `scripted` (a tool
 * name) or `scenario` (a scenario file), it runs
 * `scripts/mcp-test-server/scripted-agent.mjs` as that agent instead, signed
 * out (`scriptedLaunch`). A tool is the recorded frames; a scenario is that
 * file's steps. With `evidence`, the agent and the MCP server are wrapped by
 * `acp-recorder.mjs`, and the gateway's own log is written there before its
 * directory is removed. The credentials — the owner token, and the panel's —
 * are generated by the gateway, read from its temporary directory, never
 * printed, and removed with it.
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs"
import { join, sep } from "node:path"
import { setTimeout as sleep } from "node:timers/promises"

import {
  MODELS,
  agentCommand,
  repoRoot,
  serverScript,
  startLocalGateway,
} from "../../../../scripts/mcp-test-server/local-gateway.mjs"
import { turnEnded } from "../../../../scripts/mcp-test-server/evidence.mjs"
import { CannotRun, log } from "./cli.mjs"
import { freePort, startDevServer, startPreview } from "./server.mjs"

/**
 * The panel's credential as the gateway provisioned it: the one
 * `auth/surfaces/nessa-panel.token` under its directory, whichever namespace
 * holds it (`provisioning.rs` writes it, `surface_credential.rs` reads it for
 * the desktop window). It carries the panel's grants, not the owner's. Not
 * exactly one there is "could not run".
 */
export function panelCredential(gateway) {
  const file = join("auth", "surfaces", "nessa-panel.token")
  const found = readdirSync(gateway.directory, { recursive: true }).filter(
    (path) => String(path) === file || String(path).endsWith(sep + file),
  )
  if (found.length !== 1)
    throw new CannotRun(
      `the gateway provisioned ${found.length} panel credentials, not one`,
    )
  return readFileSync(join(gateway.directory, String(found[0])), "utf8").trim()
}

/**
 * The stack plus the panel credential. Anything thrown while that credential
 * is read, including by `fields` when it is a function, closes the stack
 * first: the caller has no target to close, and the gateway would stay up.
 */
export async function panelTarget(stack, fields = {}) {
  try {
    const extra = typeof fields === "function" ? fields() : fields
    return {
      ...stack,
      ...extra,
      credential: panelCredential(stack.gateway),
    }
  } catch (error) {
    await stack.close()
    throw error
  }
}

const recorder = join(repoRoot, "scripts/mcp-test-server/acp-recorder.mjs")

/** `argv` with `acp-recorder.mjs` writing `logPath` in front of it. */
function recorded(logPath, argv) {
  return [process.execPath, recorder, logPath, ...argv]
}

/**
 * How the gateway starts the scripted agent as `agent`'s runtime, and how it
 * starts `mcptest`. `tool` is the recorded-frame default; `scenario` is a
 * scenario file, and the two are not combined. With `evidence`, both
 * processes are wrapped so the run keeps `acp.jsonl` and `mcp.jsonl` (the
 * same direction names the live check records). Always signed out: the
 * scripted agent reads no credential.
 */
export function scriptedLaunch(agent, { tool, scenario, evidence } = {}) {
  if (!scenario && !tool) throw new Error("a scripted launch names a tool or a scenario")
  const argv = [
    process.execPath,
    join(repoRoot, "scripts/mcp-test-server/scripted-agent.mjs"),
    agent,
  ]
  if (scenario) argv.push("--scenario", scenario)
  else argv.push(tool)
  let commandArgv = argv
  let mcp = { command: process.execPath, args: [serverScript] }
  if (evidence) {
    mkdirSync(evidence, { recursive: true })
    const acp = join(evidence, "acp.jsonl")
    const mcpLog = join(evidence, "mcp.jsonl")
    writeFileSync(acp, "")
    writeFileSync(mcpLog, "")
    commandArgv = recorded(acp, argv)
    mcp = {
      command: process.execPath,
      args: [recorder, mcpLog, process.execPath, serverScript],
    }
  }
  return {
    command: { argv: commandArgv, model: MODELS[agent], path: null },
    mcp,
    signedOut: true,
  }
}

/**
 * Starts the stack as `instance`, its client named after it and signed in
 * `as` the gateway's owner (the default) or its panel. With `scripted`, a tool
 * name, the scripted agent is the runtime and calls that tool. With
 * `scenario`, it runs that file. With `evidence`, the run's logs are written
 * there. `options.mode` `prod` previews a production build; the default is a
 * dev server. Resolves with `{ url, mode, close, client, gateway, timings,
 * token }`: `url` the desktop page, `token()` the owner token, `close()`
 * stops all three. A gateway that does not start is "could not run", with
 * its last output on stderr.
 */
export async function startGatewayStack(
  options,
  instance,
  { as = "owner", scripted, scenario, evidence } = {},
) {
  const agent = options.agent
  if (!["claude", "codex"].includes(agent))
    throw new CannotRun(`--agent ${agent}: claude or codex`)
  const launch =
    scenario || scripted
      ? scriptedLaunch(agent, { tool: scripted, scenario, evidence })
      : null
  const command = launch?.command ?? agentCommand(agent)
  const timings = {}
  let started = Date.now()
  const gateway = await startLocalGateway({
    agent,
    port: await freePort(),
    instance,
    agentArgv: command.argv,
    model: command.model,
    path: command.path,
    mcpServer: launch?.mcp ?? { command: process.execPath, args: [serverScript] },
    signedOut: launch?.signedOut ?? false,
  }).catch((error) => {
    // What it said as it failed, on stderr; the result keeps one line.
    if (error.gatewayLog) log(error.gatewayLog.slice(-4000))
    if (evidence && error.gatewayLog)
      writeFileSync(join(evidence, "gateway.log"), error.gatewayLog)
    throw new CannotRun(`the gateway did not start: ${error.message.split("\n")[0]}`)
  })
  timings.gatewayMs = Date.now() - started
  let dev = null
  let client = null
  // The gateway stops, and its directory with the credentials goes, whatever
  // the client or the dev server did as they closed.
  const close = async () => {
    try {
      client?.close()
      await dev?.close()
    } finally {
      let stopped = false
      try {
        stopped = await gateway.stop()
      } finally {
        // After the stop: its last lines are in the log, and the directory
        // they are not stored in is gone. The evidence copy is this process's.
        if (evidence) writeFileSync(join(evidence, "gateway.log"), gateway.log())
        if (!stopped) log(`the gateway (pid ${gateway.server.pid}) did not exit`)
      }
    }
  }
  const token = () => readFileSync(gateway.token, "utf8").trim()
  try {
    started = Date.now()
    const stage = {
      NESSA_STAGE: "ci",
      VITE_NESSA_STAGE: "ci",
      NESSA_BROWSER_GATEWAY_URL: gateway.url,
    }
    // A production build inlines the stage. The gateway is a ci gateway, and
    // a prod stage refuses its HTTP loopback address.
    dev =
      options.mode === "prod"
        ? await startPreview(options, stage)
        : await startDevServer(options, stage)
    timings.devServerMs = Date.now() - started
    // `@nessa/client` is TypeScript in this checkout.
    const { register } = await import("tsx/esm/api")
    register()
    const { NessaClient } = await import("@nessa/client")
    client = await NessaClient.connect({
      stage: "ci",
      url: gateway.url.replace(/^http/, "ws"),
      role: "surface",
      surface: { kind: "panel", instance },
      client: { id: instance, version: "0.1.0", platform: "node" },
      profile: "product",
      auth: { credential: as === "panel" ? panelCredential(gateway) : token() },
    })
    return {
      url: dev.url,
      mode: options.mode === "prod" ? "prod" : "dev",
      close,
      client,
      gateway,
      timings,
      token,
    }
  } catch (error) {
    await close()
    throw error
  }
}

/** Waits up to `ms` for `check()` to be truthy, and says what it last was. */
export async function waitFor(check, ms) {
  const end = Date.now() + ms
  let value
  do {
    value = await check()
    if (value) return value
    await sleep(250)
  } while (Date.now() < end)
  return value
}

/**
 * Sends `text` in `conversationId` — creating the conversation first when
 * `create` — and reads the conversation each second until that turn ends,
 * handing each read to `onView` (which may answer the turn's permissions).
 * `ready(view, turn)` returns the view before the turn ends, for a step that
 * has to act while it is still running. Resolves with `{ view, turn }`: the
 * view in which the turn ended or became ready, and the turn; whether it
 * ended well is the caller's to judge. A conversation or message the gateway
 * refuses, or a turn that does neither within `seconds`, is "could not run".
 */
export async function agentTurn(
  client,
  conversationId,
  text,
  { agent, create = false, seconds = 180, onView = async () => {}, ready = () => false },
) {
  let before
  try {
    if (create) await client.conversation.create({ conversationId, agent })
    // The view's messages are its turns; this one is the one after `before`.
    before = (await client.conversation.read(conversationId)).messages.length
    await client.conversation.send(conversationId, text)
  } catch (error) {
    throw new CannotRun(
      `the gateway refused the ${agent} conversation (a live ${agent}: is it signed in on this machine?): ${error.message}`,
    )
  }
  let turn
  for (let i = 0; i < seconds; i += 1) {
    await sleep(1000)
    const view = await client.conversation.read(conversationId)
    await onView(view)
    turn = view.messages[before]
    if (turn && (ready(view, turn) || turnEnded(turn.status))) return { view, turn }
  }
  throw new CannotRun(
    `${agent}'s turn did not end within ${seconds} s; it was last ${turn?.status ?? "not listed"}`,
  )
}
