//! Owner commands derive canonical consent from current authenticated identity.
use nessa_auth::{
    application::{
        pairing::{
            AuthorizePairing, OwnerDecision, PairingAdmission, PairingStore, PairingStoreError,
        },
        ports::{AccessError, Clock},
        session::AuthenticatedSession,
    },
    domain::{
        pairing::{
            validate_pairing_collection, ConsentIntent, ConsentIntentId, InvitationId,
            PairingError, PairingPolicy, PairingRecord,
        },
        Resource,
    },
};
/// Typed refusal at the owner operation boundary; no provider diagnostics.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum OwnerError {
    /// Current session or exact intent is no longer authorized.
    Authorization(AccessError),
    /// Canonical registry read or conditional mutation refused.
    Enrollment(PairingStoreError),
    /// Generated immutable identity/policy or collection admission refused.
    Domain(PairingError),
}
/// Current admission held across code registration. It creates no durable
/// invitation, and its private fields mean only `PairingOwner::prepare` makes one.
pub struct PreparedInvitation {
    record: PairingRecord,
    admission: PairingAdmission,
}
impl PreparedInvitation {
    /// Read immutable public context for registering this exact generated invite.
    pub fn record(&self) -> &PairingRecord {
        &self.record
    }
}
/// The owner API shares current auth policy and the canonical invitation store.
pub struct PairingOwner<'a> {
    /// Current session/membership/grant policy owner, reevaluated per command.
    pub authorization: AuthorizePairing<'a>,
    /// Existing registry owner; writes retain its revision CAS and audit history.
    pub enrollments: &'a dyn PairingStore,
    /// The gateway resource, chosen by composition rather than by the request.
    pub gateway: &'a Resource,
    /// Composition-selected finite invitation policy.
    pub policy: PairingPolicy,
    /// Injected absolute clock, sampled again by canonical mutation owner.
    pub clock: &'a dyn Clock,
}
impl PairingOwner<'_> {
    /// Prepare one fresh immutable intent. IDs are generated by the runtime's
    /// entropy owner, not decoded into an authority capability from client input.
    /// The domain collection owner is asked before expensive physical registration;
    /// the canonical registry repeats that decision against its mutation snapshot.
    pub async fn prepare(
        &self,
        session: &AuthenticatedSession,
        id: InvitationId,
        consent: ConsentIntentId,
    ) -> Result<PreparedInvitation, OwnerError> {
        let context = session.context();
        let intent = ConsentIntent::new(
            consent,
            1,
            context.audience_id().clone(),
            context.principal_id().clone(),
            context.membership_id().clone(),
            self.gateway.clone(),
        )
        .map_err(OwnerError::Domain)?;
        let admission = self
            .authorization
            .execute(session, &intent, self.gateway)
            .await
            .map_err(OwnerError::Authorization)?;
        let record = PairingRecord::new(id, intent, self.clock.unix_milliseconds(), self.policy)
            .map_err(OwnerError::Domain)?;
        let mut records = self
            .enrollments
            .pending_pairings()
            .map_err(OwnerError::Enrollment)?
            .into_vec();
        records.push(record.clone());
        validate_pairing_collection(&records).map_err(OwnerError::Domain)?;
        Ok(PreparedInvitation { record, admission })
    }
    /// Commit after successful physical registration, before local code display.
    /// An intervening auth mutation refuses the original admission; no success or
    /// code acknowledgement may be published from the discarded registration.
    pub async fn create(&self, prepared: PreparedInvitation) -> Result<PairingRecord, OwnerError> {
        self.enrollments
            .create_pairing(&prepared.record, &prepared.admission, self.clock)
            .await
            .map_err(OwnerError::Enrollment)
    }
    /// Select immutable current-owner candidates, then ask full current admission.
    /// A selector match grants nothing by itself: each match is then read through
    /// `status`, which asks current session and policy.
    pub async fn pending(
        &self,
        session: &AuthenticatedSession,
    ) -> Result<Box<[PairingRecord]>, OwnerError> {
        let records = self
            .enrollments
            .pending_pairings()
            .map_err(OwnerError::Enrollment)?;
        let context = session.context();
        let mut admitted = Vec::new();
        for record in records {
            if record.intent().matches_owner(
                context.principal_id(),
                context.membership_id(),
                context.audience_id(),
                context.organization_id(),
                self.gateway,
            ) {
                admitted.push(self.status(session, record.id()).await?);
            }
        }
        Ok(admitted.into_boxed_slice())
    }
    /// Read protected enrollment history only after current exact-intent admission.
    pub async fn status(
        &self,
        session: &AuthenticatedSession,
        id: InvitationId,
    ) -> Result<PairingRecord, OwnerError> {
        let record = self
            .enrollments
            .read_pairing(id)
            .map_err(OwnerError::Enrollment)?;
        self.authorization
            .execute(session, record.intent(), self.gateway)
            .await
            .map_err(OwnerError::Authorization)?;
        Ok(record)
    }
    /// Record explicit approval of an exact displayed key, denial, or cancellation.
    /// Existing registry behavior atomically revokes an Active key on cancellation;
    /// its independent physical cleanup obligation remains visible for the runtime.
    pub async fn decide(
        &self,
        session: &AuthenticatedSession,
        id: InvitationId,
        decision: OwnerDecision,
    ) -> Result<PairingRecord, OwnerError> {
        let record = self
            .enrollments
            .read_pairing(id)
            .map_err(OwnerError::Enrollment)?;
        let admission = self
            .authorization
            .execute(session, record.intent(), self.gateway)
            .await
            .map_err(OwnerError::Authorization)?;
        self.enrollments
            .decide_pairing(id, decision, &admission, self.clock)
            .await
            .map_err(OwnerError::Enrollment)
    }
}
