use std::{error::Error, fmt};

/// JSON-RPC identity assigned by the configured provider to one MCP tool call.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ToolRequestId {
    /// Negative numeric JSON-RPC identity.
    Signed(i64),
    /// Nonnegative numeric JSON-RPC identity.
    Unsigned(u64),
    /// Nonempty bounded textual JSON-RPC identity.
    Text(Box<str>),
}

/// Invalid trusted-transport correlation evidence.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ToolInvocationError;
impl fmt::Display for ToolInvocationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("tool invocation identity is empty or exceeds 256 bytes")
    }
}
impl Error for ToolInvocationError {}

/// Verified initiator class for an invocation admitted from the private provider transport.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ToolInitiator {
    /// The configured provider issued this tool call on its private stdio connection.
    ConfiguredProviderToolCall,
}

/// Stable correlation and honest initiator for one provider-originated tool call.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ToolInvocation {
    connection_id: Box<str>,
    request_id: ToolRequestId,
}
impl ToolInvocation {
    /// Correlate a call received from the configured private stdio provider.
    /// `connection_id` is generated by Nessa composition, never accepted from MCP metadata.
    pub fn provider(
        connection_id: impl Into<String>,
        request_id: ToolRequestId,
    ) -> Result<Self, ToolInvocationError> {
        let connection_id = connection_id.into();
        let request_valid = !matches!(&request_id, ToolRequestId::Text(value) if value.is_empty() || value.len() > 256);
        if connection_id.is_empty() || connection_id.len() > 256 || !request_valid {
            return Err(ToolInvocationError);
        }
        Ok(Self {
            connection_id: connection_id.into_boxed_str(),
            request_id,
        })
    }
    /// Nessa-generated identity for this private provider connection.
    pub fn connection_id(&self) -> &str {
        &self.connection_id
    }
    /// Provider-assigned JSON-RPC request identity within this connection.
    pub fn request_id(&self) -> &ToolRequestId {
        &self.request_id
    }
    /// Verified initiator supplied by composition rather than untrusted MCP metadata.
    pub fn initiator(&self) -> ToolInitiator {
        ToolInitiator::ConfiguredProviderToolCall
    }
}

#[cfg(test)]
#[path = "../../../tests/shell/domain/identity.rs"]
mod tests;
