import assert from "node:assert/strict"
import { execFileSync } from "node:child_process"
import { readFileSync } from "node:fs"
import test from "node:test"

import { documentationOnly } from "./documentation-only.mjs"

/**
 * This gate decides whether roughly thirty minutes of compilation runs. Every
 * test here is about the direction it is allowed to be wrong in: skipping a
 * check that would have failed is silent, running one that could not have
 * failed only costs time. So the cases below are mostly about what does *not*
 * count as documentation.
 */

test("a change confined to Markdown skips the compile-heavy jobs", () => {
  assert.equal(documentationOnly(["README.md"]), true)
  assert.equal(documentationOnly(["docs/ARCHITECTURE.md", "AGENTS.md"]), true)
  assert.equal(documentationOnly(["crates/nessa-sdk/docs/claude-acp.md"]), true)
})

/**
 * A crate's README sits beside its source and is the file most likely to be
 * mistaken for code — `#![doc = include_str!("../README.md")]` is a common
 * enough pattern that the answer here is a fact about this repository rather
 * than about Rust. `documentation-only.mjs` records why it holds; the check
 * below is what notices when it stops holding.
 */
test("no crate embeds a Markdown file, which is what makes Markdown inert", () => {
  const sources = execFileSync(
    "git",
    ["ls-files", "crates/*.rs", "src-tauri/*.rs", "*.rs"],
    { cwd: new URL("..", import.meta.url), encoding: "utf8" },
  )
    .split("\n")
    .filter((path) => path.endsWith(".rs"))
  const embedding = sources.filter((path) => {
    const text = readFileSync(new URL(`../${path}`, import.meta.url), "utf8")
    return (
      /include_str!\s*\(\s*"[^"]*\.md"/.test(text) || /doc\s*=\s*include_str/.test(text)
    )
  })
  assert.deepEqual(
    embedding,
    [],
    "a crate now compiles a Markdown file in, so Markdown is no longer inert:\n" +
      "  teach scripts/documentation-only.mjs to stop skipping on it.",
  )
})

/**
 * `docs/` is not the rule, the extension is. `docs/generated/client-api.json`
 * is regenerated by `pnpm client:docs:json` and compared by
 * `scripts/check-client-docs.mjs`, so a change to it is a change CI can fail
 * on. A rule written as "anything under docs/" would have skipped that.
 */
test("a non-Markdown file under docs/ still runs everything", () => {
  assert.equal(documentationOnly(["docs/generated/client-api.json"]), false)
  assert.equal(
    documentationOnly(["docs/README.md", "docs/generated/client-api.json"]),
    false,
  )
})

test("one source file among the prose runs everything", () => {
  assert.equal(documentationOnly(["README.md", "crates/nessa-sdk/src/lib.rs"]), false)
  assert.equal(
    documentationOnly(["README.md", ".github/workflows/local-auth.yml"]),
    false,
  )
  assert.equal(documentationOnly(["README.md", "Cargo.lock"]), false)
  assert.equal(documentationOnly(["README.md", "scripts/documentation-only.mjs"]), false)
})

/**
 * A name ending in `.md` is not the same as a Markdown file, but the ways it
 * can differ here are all harmless: `mdbook.md` is prose, and a directory
 * cannot appear in `git diff --name-only`. What is worth pinning is that the
 * suffix is matched at the end and nowhere else.
 */
test("a path that merely contains .md is not Markdown", () => {
  assert.equal(documentationOnly(["src/md.ts"]), false)
  assert.equal(documentationOnly(["scripts/render.md.mjs"]), false)
  assert.equal(documentationOnly(["crates/nessa-sdk/src/markdown.rs"]), false)
})

/**
 * Nothing reported changed is indistinguishable from nothing being reported —
 * a diff taken against the wrong base, a paginated API call that returned an
 * empty page — and only one of those two wants the checks skipped.
 */
test("an empty or blank change list runs everything", () => {
  assert.equal(documentationOnly([]), false)
  assert.equal(documentationOnly([""]), false)
  assert.equal(documentationOnly(["", "  ", "\t"]), false)
})

test("blank lines around real paths are ignored, not counted", () => {
  assert.equal(documentationOnly(["README.md", "", "docs/README.md", ""]), true)
  assert.equal(documentationOnly(["", "src/main.tsx", ""]), false)
})

/** The workflow consumes stdout verbatim into `$GITHUB_OUTPUT`. */
test("the command prints exactly the word a workflow expects", () => {
  const script = new URL("documentation-only.mjs", import.meta.url)
  const run = (input) =>
    execFileSync("node", [script.pathname], { input, encoding: "utf8" })
  assert.equal(run("README.md\ndocs/README.md\n"), "true")
  assert.equal(run("README.md\nsrc/main.tsx\n"), "false")
  assert.equal(run(""), "false")
})
