[package]
name = "nessa-local-storage"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
getrandom = "0.3"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security", "Win32_Security_Authorization", "Win32_Storage_FileSystem", "Win32_System_Threading"] }

[dev-dependencies]
tempfile = "3"
